### ISSUE TITLE
Educational: Add documentation section about how to block internet access to the GAFAMs

### ISSUE THREAD

**Issue by amotl** [gafam/www.gafam.info#3]
Hi.

In the same spirit as #2, this project could provide some information about software and services which intentionally protect users from the GAFAMs, for example by means of internet access blocking.

For example, @nickspaargaren maintains the [no-google] and [no-amazon] repositories, which both host network blocklists to be used, for example, with the [Pi-hole] project.

With kind regards,
Andreas.

[no-google]: https://github.com/nickspaargaren/no-google
[no-amazon]: https://github.com/nickspaargaren/no-amazon
[Pi-hole]: https://pi-hole.net/

**Comment by nickspaargaren** [comment]
Hi @amotl, can you assign me to this issue?

**Comment by nickspaargaren** [comment]
Hi @amotl, the [webpage](https://gafam.info) is mainly about the GAFAM poster campaign. What's your vision on adding the "block internet access" content?

**Comment by amotl** [comment]
Hi Nick,

right, the webpage is currently exclusively about the poster campaign. However, I thought about adding a few educational sections. In this specific section, I thought it would be a good idea to outline projects like those from your pen, specifically the `no-google` and `no-amazon` block lists, and how to use them.

If you have other ideas how to populate that new section, feel free to go crazy about it.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Thank you for submitting GH-16. Your improvements have just been published.
